
name: CI Build

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  build-uclibc:
    name: Build libretro cores for Miyoo (musl)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-musl
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: fetch & compile cores
      run: make release
    - name: output "log/libretro-super"
      run: |
        cat log/libretro-super.log